title: Cocoataster
author:
  name: Cocoataster
  email: me@cocoataster.com
url: "https://cocoataster.com"

# The `>` after `description:` means to ignore line-breaks until next key.
# If you want to omit the line-break after the end of text, use `>-` instead.
# description: >
#   Write an awesome description for your new site here. You can edit this line
#   in _config.yml. It will appear in your document head meta (for Google search
#   results) and in your feed.xml site description.

# Build settings

theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Theme-specific settings

minima:
  skin: dark
  # Minima date format.
  # Refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this.
  #
  # date_format: "%b %-d, %Y"

  # Generate social links in footer.
  #
  social_links:
  #   - { platform: devto,          user_url: "https://dev.to/jekyll" }
  #   - { platform: dribbble,       user_url: "https://dribbble.com/jekyll" }
  #   - { platform: facebook,       user_url: "https://www.facebook.com/jekyll" }
  #   - { platform: flickr,         user_url: "https://www.flickr.com/photos/jekyll" }
    - { platform: github,         user_url: "https://github.com/cocoataster" }
  #   - { platform: google_scholar, user_url: "https://scholar.google.com/citations?user=qc6CJjYAAAAJ" }
  #   - { platform: instagram,      user_url: "https://www.instagram.com/jekyll" }
  #   - { platform: keybase,        user_url: "https://keybase.io/jekyll" }
  #   - { platform: linkedin,       user_url: "https://www.linkedin.com/in/jekyll" }
  #   - { platform: microdotblog,   user_url: "https://micro.blog/jekyll" }
  #   - { platform: pinterest,      user_url: "https://www.pinterest.com/jekyll" }
  #   - { platform: stackoverflow,  user_url: "https://stackoverflow.com/users/1234567/jekyll" }
  #   - { platform: telegram,       user_url: "https://t.me/jekyll" }
    - { platform: twitter,        user_url: "https://x.com/cocoataster" }
    - { platform: bluesky,        user_url: "https://bsky.app/profile/cocoataster.bsky.social" }
  #   - { platform: youtube,        user_url: "https://www.youtube.com/jekyll" }

# Apps displayed on the homepage
apps:
  - name: Impulses
    id: impulses
    icon: /assets/icons/impulses.png
    tagline: Track habits and daily impulses
    url: "https://cocoataster.com/impulses/"
  - name: Meals
    id: meals
    icon: /assets/icons/meals.png
    tagline: Simple and visual meal logging
    url: "https://www.cocoataster.com/meals"
  - name: QuickScore
    id: quickscore
    icon: /assets/icons/quickscore.png
    tagline: Fast and easy scorekeeping
    url: "https://www.cocoataster.com/quick-score-landing"

# If you want to link only specific pages in your header, uncomment this and add the path to the pages in
# order as they should show up.
#
header_pages:
  - posts.html
  - about.md

# Set to `true` to show excerpts on the homepage.
#
# show_excerpts: false
